import { AppProps } from "next/app";
import Head from "next/head";
import "../pages/styles/globals.css";
import { DragDropContext } from "react-beautiful-dnd";

export default function App({ Component, pageProps }: AppProps) {
    const onDragEnd = () => {
    };    return (
        <>
          <Head>
            <title>Soostone</title>
            <meta name="description" content="Generated by ovinot" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon_ovi.ico" />
          </Head>
          <main>
            <DragDropContext onDragEnd={onDragEnd}>
              <Component {...pageProps} />
            </DragDropContext>
          </main>
        </>
      );
    }